import { createStackNavigator } from '@react-navigation/stack';
import React, {FC} from 'react';
import * as Screens from '../screens';
import BottomTabMain from './BottomTabMain';

const RootStack = createStackNavigator();

const AppNavigator: FC = () => {
  return (
    <RootStack.Navigator
      screenOptions={{ headerShown: false }}
      // initialRouteName='BottomTabMain'
    // initialRouteName='Profile'
    >

      <RootStack.Screen
        name="Splash"
        component={Screens.Splash}
      />
      <RootStack.Screen
        name="Onboarding"
        component={Screens.OnBoarding}
      />
      <RootStack.Screen
        name="RegisterPlan"
        component={Screens.RegisterPlan}
      />
      <RootStack.Screen
        name="RegisterDecision"
        component={Screens.RegisterDecision}
      />
      <RootStack.Screen
        name="RegisterConnect"
        component={Screens.RegisterConnect}
      />
      <RootStack.Screen
        name="RegisterAtmPin"
        component={Screens.RegisterAtmPin}
      />
      <RootStack.Screen
        name="RegisterMaxPin"
        component={Screens.RegisterMaxPin}
      />
      <RootStack.Screen
        name="RegisterSchedule"
        component={Screens.RegisterSchedule}
      />
      <RootStack.Screen
        name="RegisterProgress"
        component={Screens.RegisterProgress}
      />
      <RootStack.Screen
        name="RegisterCreate"
        component={Screens.RegisterCreate}
      />
      <RootStack.Screen
        name="RegisterPersonalInformation"
        component={Screens.RegisterPersonalInformation}
      />
      <RootStack.Screen
        name="GoToLogin"
        component={Screens.GoToLogin}
      />
      <RootStack.Screen
        name="VerifyAccountMobile"
        component={Screens.VerifyAccountMobile}
      />
      <RootStack.Screen
        name="VerifyAccountEmail"
        component={Screens.VerifyAccountEmail}
      />
      <RootStack.Screen
        name="UploadKtp"
        component={Screens.UploadKtp}
      />
      <RootStack.Screen
        name="PreviewKtp"
        component={Screens.PreviewKtp}
      />
      <RootStack.Screen
        name="ReviewKtp"
        component={Screens.ReviewKtp}
      />
      <RootStack.Screen
        name="CustomPrintedName"
        component={Screens.CustomPrintedName}
      />
      <RootStack.Screen
        name="DataConfirmation"
        component={Screens.DataConfirmation}
      />
      <RootStack.Screen
        name="CreatePassword"
        component={Screens.CreatePassword}
      />
      <RootStack.Screen
        name="CreateTransactionPin"
        component={Screens.CreateTransactionPin}
      />
      <RootStack.Screen
        name="RetransactionPin"
        component={Screens.ReTransactionPin}
      />
      <RootStack.Screen
        name="TermCondition"
        component={Screens.TermCondition}
      />
      <RootStack.Screen
        name="AccountVerification"
        component={Screens.AccountVerification}
      />
      <RootStack.Screen
        name="RegisterSent"
        component={Screens.RegisterSent}
      />
      <RootStack.Screen
        name="RescheduleVidcall"
        component={Screens.ReScheduleVidCall}
      />
      <RootStack.Screen
        name="PersonalInformation"
        component={Screens.PersonalInformation}
      />
      <RootStack.Screen
        name="UploadDocuments"
        component={Screens.UploadDocuments}
      />
      <RootStack.Screen
        name="UserForm1"
        component={Screens.UserForm_1}
      />
      <RootStack.Screen
        name="UserForm2"
        component={Screens.UserForm_2}
      />
      <RootStack.Screen
        name="UserForm3"
        component={Screens.UserForm_3}
      />
      <RootStack.Screen
        name="UserForm4"
        component={Screens.UserForm_4}
      />
      <RootStack.Screen
        name="UserForm5"
        component={Screens.UserForm_5}
      />
      <RootStack.Screen
        name="UserForm6"
        component={Screens.UserForm_6}
      />
      <RootStack.Screen
        name="OccupationInfo1"
        component={Screens.OccupationInfo_1}
      />
      <RootStack.Screen
        name="OccupationInfo2"
        component={Screens.OccupationInfo_2}
      />
      <RootStack.Screen
        name="OccupationInfo3"
        component={Screens.OccupationInfo_3}
      />
      <RootStack.Screen
        name="OccupationInfo4"
        component={Screens.OccupationInfo_4}
      />
      <RootStack.Screen
        name="OccupationInfo5"
        component={Screens.OccupationInfo_5}
      />
      <RootStack.Screen
        name="OccupationInfo6"
        component={Screens.OccupationInfo_6}
      />
      <RootStack.Screen
        name="OccupationInfo7"
        component={Screens.OccupationInfo_7}
      />
      <RootStack.Screen
        name="OccupationInfo8"
        component={Screens.OccupationInfo_8}
      />
      <RootStack.Screen
        name="ChoosePlan"
        component={Screens.ChoosePlan}
      />
      <RootStack.Screen
        name="CardDesign"
        component={Screens.CardDesign}
      />
      <RootStack.Screen
        name="Home"
        component={Screens.Home}
      />
      <RootStack.Screen
        name="TransferTo"
        component={Screens.TransferTo}
      />
      <RootStack.Screen
        name="NewReceipt"
        component={Screens.NewReceipt}
      />
      <RootStack.Screen
        name="Transfer"
        component={Screens.Transfer}
      />
      <RootStack.Screen
        name="TransferFrom"
        component={Screens.TransferFrom}
      />
      <RootStack.Screen
        name="Voucher"
        component={Screens.Voucher}
      />
      <RootStack.Screen
        name="TransferConfirmation"
        component={Screens.TransferConfirmation}
      />
      <RootStack.Screen
        name="TransactionPin"
        component={Screens.TransactionPin}
      />
      <RootStack.Screen
        name="TransferSuccess"
        component={Screens.TransferSuccess}
      />
      <RootStack.Screen
        name="TransferSuccessScheduled"
        component={Screens.TransferSuccessScheduled}
      />
      <RootStack.Screen
        name="TransferFailed"
        component={Screens.TransferFailed}
      />
      <RootStack.Screen
        name="TransferFailedScheduled"
        component={Screens.TransferFailedScheduled}
      />
      <RootStack.Screen
        name="AddFavorit"
        component={Screens.AddFavorit}
      />
      <RootStack.Screen
        name="PreviewSuccessTransfer"
        component={Screens.PreviewSuccessTransfer}
      />
      <RootStack.Screen
        name="AddFrom"
        component={Screens.AddFrom}
      />
      <RootStack.Screen
        name="AddBalance"
        component={Screens.AddBalance}
      />
      <RootStack.Screen
        name="BalanceConfirmation"
        component={Screens.BalanceConfirmation}
      />
      <RootStack.Screen
        name="AddBalanceFromOther"
        component={Screens.AddBalanceFromOther}
      />
      <RootStack.Screen
        name="InfoTransfer"
        component={Screens.InfoTransfer}
      />
      <RootStack.Screen
        name="MoveBalance"
        component={Screens.MoveBalance}
      />
      <RootStack.Screen
        name="ChooseAccount"
        component={Screens.ChooseAccount}
      />
      <RootStack.Screen
        name="VirtualAccount"
        component={Screens.VirtualAccount}
      />
      <RootStack.Screen
        name="ChooseAccountType"
        component={Screens.ChooseAccountType}
      />
      <RootStack.Screen
        name="CreatePocket"
        component={Screens.CreatePocket}
      />
      <RootStack.Screen
        name="CreatePocketConfirmation"
        component={Screens.CreatePocketConfirmation}
      />
      <RootStack.Screen
        name="CreatePocketSuccess"
        component={Screens.CreatePocketSuccess}
      />
      <RootStack.Screen
        name="ChooseTabka"
        component={Screens.ChooseTabka}
      />
      <RootStack.Screen
        name="CreateTabkaFlex"
        component={Screens.CreateTabkaFlex}
      />
      <RootStack.Screen
        name="CreateTabkaConfirmation"
        component={Screens.CreateTabkaConfirmation}
      />
      <RootStack.Screen
        name="TabkaCreated"
        component={Screens.TabkaCreated}
      />
      <RootStack.Screen
        name="ChoosePrize"
        component={Screens.ChoosePrize}
      />
      <RootStack.Screen
        name="CreateTabkaPrize"
        component={Screens.CreateTabkaPrize}
      />
      <RootStack.Screen
        name="CreateDeposito"
        component={Screens.CreateDeposito}
      />
      <RootStack.Screen
        name="CreateDepositoConfirmation"
        component={Screens.CreateDepositoConfirmation}
      />
      <RootStack.Screen
        name="DepositoCreated"
        component={Screens.DepositoCreated}
      />
      <RootStack.Screen
        name="ChooseBmSavings"
        component={Screens.ChooseBMSsavings}
      />
      <RootStack.Screen
        name="CreateBmSavings"
        component={Screens.CreateBMSavings}
      />
      <RootStack.Screen
        name="CreateBmSavingsConfirmation"
        component={Screens.CreateBMSavingsConfirmation}
      />
      <RootStack.Screen
        name="BmSavingsCreated"
        component={Screens.BMSavingsCreated}
      />
      <RootStack.Screen
        name="PayBuy"
        component={Screens.PayBuy}
      />
      <RootStack.Screen
        name="Prepaid"
        component={Screens.Prepaid}
      />
      <RootStack.Screen
        name="Postpaid"
        component={Screens.Postpaid}
      />
      <RootStack.Screen
        name="NonTaglis"
        component={Screens.NonTaglis}
      />
      <RootStack.Screen
        name="UpdateBalance"
        component={Screens.UpdateBalance}
      />
      <RootStack.Screen
        name="BisaCashHistory"
        component={Screens.BisaCashHistory}
      />
      <RootStack.Screen
        name="ScanQr"
        component={Screens.ScanQR}
      />
      <RootStack.Screen
        name="PayQrWithAmount"
        component={Screens.PayQrWithAmount}
      />
      <RootStack.Screen
        name="PayQrNoAmount"
        component={Screens.PayQrNoAmount}
      />
      <RootStack.Screen
        name="SendRequest"
        component={Screens.SendRequest}
      />
      <RootStack.Screen
        name="RequestMoney"
        component={Screens.RequestMoneyFor}
      />
      <RootStack.Screen
        name="RequestMoneyStatus"
        component={Screens.RequestMoneyStatus}
      />
      <RootStack.Screen
        name="Login"
        component={Screens.Login}
      />
      <RootStack.Screen
        name="PasswordMax"
        component={Screens.PasswordMax}
      />
      <RootStack.Screen
        name="ActiveBiometrics"
        component={Screens.ActiveBiometrics}
      />
      <RootStack.Screen
        name="BiometricsActivated"
        component={Screens.BiometricsActivated}
      />
      <RootStack.Screen
        name="ForgotPassword"
        component={Screens.ForgotPassword}
      />
      <RootStack.Screen
        name="CreateNewPassword"
        component={Screens.CreateNewPassword}
      />
      <RootStack.Screen
        name="StatusSuccessful"
        component={Screens.StatusSuccessful}
      />
      <RootStack.Screen
        name="BottomTabMain"
        component={BottomTabMain}
      />
      <RootStack.Screen
        name="ActiveCard"
        component={Screens.ActiveCard}
      />
      <RootStack.Screen
        name="HomeSwiped"
        component={Screens.HomeSwiped}
      />
      <RootStack.Screen
        name="ActivatedCard"
        component={Screens.ActivatedCard}
      />
      <RootStack.Screen
        name="CreateAtmPin"
        component={Screens.CreateAtmPin}
      />
      <RootStack.Screen
        name="ReEnterAtmPin"
        component={Screens.ReEnterAtmPin}
      />
      <RootStack.Screen
        name="UnblockAccount"
        component={Screens.UnblockAccount}
      />
      <RootStack.Screen
        name="PocketVacation"
        component={Screens.PocketVacation}
      />
      <RootStack.Screen
        name="EditPocket"
        component={Screens.EditPocket}
      />
      <RootStack.Screen
        name="GiroRupiah"
        component={Screens.GiroRupiah}
      />
      <RootStack.Screen
        name="ManageAccount"
        component={Screens.ManageAccount}
      />
      <RootStack.Screen
        name="TabunganPendidikan"
        component={Screens.TabunganPendidikan}
      />
      <RootStack.Screen
        name="WithdrawConfirmation"
        component={Screens.WithdrawConfirmation}
      />
      <RootStack.Screen
        name="Deposito"
        component={Screens.Deposito}
      />
      <RootStack.Screen
        name="MaturityInstruction"
        component={Screens.MaturityInsturction}
      />
      <RootStack.Screen
        name="Kpr"
        component={Screens.Kpr}
      />
      <RootStack.Screen
        name="Favorite"
        component={Screens.Favorite}
      />
      <RootStack.Screen
        name="FavoriteProfile"
        component={Screens.FavoriteProfile}
      />
      <RootStack.Screen
        name="FavoriteProfileEdit"
        component={Screens.FavoriteProfileEdit}
      />
      <RootStack.Screen
        name="Notification"
        component={Screens.Notification}
      />
      <RootStack.Screen
        name="NewsDetail"
        component={Screens.NewsDetail}
      />
      <RootStack.Screen
        name="IncomingRequest"
        component={Screens.IncomingRequest}
      />
      <RootStack.Screen
        name="VerifyWithdrawal"
        component={Screens.VerifyWithdrawal}
      />
      <RootStack.Screen
        name="ListVoucher"
        component={Screens.ListVoucher}
      />
      <RootStack.Screen
        name="VoucherDetail"
        component={Screens.VoucherDetail}
      />
      <RootStack.Screen
        name="CashWithdrawal"
        component={Screens.CashWithdrawal}
      />
      <RootStack.Screen
        name="WithdrawalCode"
        component={Screens.WithdrawCode}
      />
      <RootStack.Screen
        name="WithdrawCashInstruction"
        component={Screens.WithdrawCashInstruction}
      />
      <RootStack.Screen
        name="VerifyCashWithdrawal"
        component={Screens.VerifyCashWithdrawal}
      />
      <RootStack.Screen
        name="TopupCash"
        component={Screens.TopupCash}
      />
      <RootStack.Screen
        name="TopupCode"
        component={Screens.TopupCode}
      />
      <RootStack.Screen
        name="TopupInstruction"
        component={Screens.TopupCashInstruction}
      />
      <RootStack.Screen
        name="VerifyCashTopup"
        component={Screens.VerifyCashTopup}
      />
      <RootStack.Screen
        name="Profile"
        component={Screens.Profile}
      />
      <RootStack.Screen
        name="ChangeNickname"
        component={Screens.ChangeNickname}
      />
      <RootStack.Screen
        name="CompleteReqSent"
        component={Screens.CompleteReqSent}
      />
      <RootStack.Screen
        name="ChangeEmail"
        component={Screens.ChangeEmail}
      />
      <RootStack.Screen
        name="ChangePassword"
        component={Screens.ChangePassword}
      />
      <RootStack.Screen
        name="ChangeAddress"
        component={Screens.ChangeAddress}
      />
      <RootStack.Screen
        name="ChangeMobileNumber"
        component={Screens.ChangeMobileNumber}
      />
      <RootStack.Screen
        name="ScheduledTransaction"
        component={Screens.ScheduledTransaction}
      />
      <RootStack.Screen
        name="ScheduledTransactionDetail"
        component={Screens.ScheduledTransactionDetail}
      />
      <RootStack.Screen
        name="EditTransaction"
        component={Screens.EditTransaction}
      />
      <RootStack.Screen
        name="Help"
        component={Screens.Help}
      />
      <RootStack.Screen
        name="SendEmail"
        component={Screens.SendEmail}
      />
      <RootStack.Screen
        name="TopicDetail"
        component={Screens.TopicsDetail}
      />
      <RootStack.Screen
        name="FaqAnswer"
        component={Screens.FaqAnswer}
      />
      <RootStack.Screen
        name="AboutApp"
        component={Screens.AboutApp}
      />
      <RootStack.Screen
        name="Privacy"
        component={Screens.Privacy}
      />
      <RootStack.Screen
        name="IncomingVideoCall"
        component={Screens.IncomingVideoCall}
      />
      <RootStack.Screen
        name="VideoCallOngoing"
        component={Screens.VideoCallOngoing}
      />
    </RootStack.Navigator>
  );
};

export default AppNavigator;
